input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Assure que @timestamp existe pour Elasticsearch
  if ![@timestamp] {
    mutate {
      add_field => { "@timestamp" => "%{+YYYY-MM-dd'T'HH:mm:ss.SSSZ}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logback-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Affiche les logs pour debug
}
